receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed
  otlp/dashboard:
    endpoint: ${env:DASHBOARD_URL}
    tls:
      insecure: true
  otlp:
    endpoint: ${env:TEMPO_URL}
    tls:
      insecure: true
  loki:
    endpoint: ${env:LOKI_URL}
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki, otlp/dashboard, debug]
    traces:
      receivers: [otlp]
      exporters: [otlp, otlp/dashboard, debug]