receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      # http:
      #   endpoint: 0.0.0.0:4318

  # prometheus:
  #   trim_metric_suffixes: true
  #   use_start_time_metric: true
  #   start_time_metric_regex: .*
  #   config:
  #     scrape_configs:
  #       - job_name: 'otel-collector-metrics'
  #         scrape_interval: 5s
  #         static_configs:
  #           - targets: ['127.0.0.1:8888']

exporters:
  debug:
    verbosity: detailed
  otlp/dashboard:
    endpoint: ${env:DASHBOARD_URL}
    tls:
      insecure: true    
  otlp:
    endpoint: ${env:TEMPO_URL}
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: ${env:LOKI_URL}
    tls:
      insecure: true
  # prometheus:
  #   endpoint: 0.0.0.0:8889

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs, otlp/dashboard, debug]
    # metrics:
    #   receivers: [prometheus, otlp]
    #   processors: [batch]
    #   exporters: [prometheus, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, otlp/dashboard, debug]