receivers:
  otlp:
    protocols:
      grpc:
  prometheus:
    trim_metric_suffixes: true
    use_start_time_metric: true
    start_time_metric_regex: .*
    config:
      scrape_configs:
        - job_name: 'otel-collector-metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['127.0.0.1:8888']

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: ${env:TEMPO_URL}
    tls:
      insecure: true
  loki:
    endpoint: ${env:LOKI_URL}
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: default

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki,debug]
    metrics:
      receivers: [prometheus,otlp]
      processors: [batch]
      exporters: [prometheus,debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]