# global:
#   external_labels:
#     basket_url: ${BASKET_URL}
global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
  - job_name: otel-collector
    static_configs:
    - targets:
      - host.docker.internal:8888
      - host.docker.internal:8889
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://host.docker.internal:5251/health #Catalog API
        - http://host.docker.internal:5252/health #Basket API
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115