#https://grafana.com/docs/grafana/latest/administration/provisioning/
apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  url: http://host.docker.internal:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false

- name: Loki
  type: loki
  uid: loki
  access: proxy
  url: http://host.docker.internal:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: "\u0022traceid\u0022:\u0022(\\w+)\u0022"
        name: TraceId
        url: '$${__value.raw}'