services:
  blackbox:
    # https://github.com/prometheus/blackbox_exporter/releases
    image: prom/blackbox-exporter:v0.24.0
    container_name: blackbox
    restart: unless-stopped
    ports:
      - 9115:9115
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/otel/blackbox.yml:/etc/blackbox/blackbox.yml
    command: --config.file=/etc/blackbox/blackbox.yml
    networks:
      - otel
     
  prometheus:
    # https://github.com/prometheus/prometheus/releases
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/otel/prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/lib/docker/volumes/otel/prometheus:/prometheus
    depends_on:
      - blackbox
    networks:
      - otel
      
  tempo:
    # https://github.com/grafana/tempo/releases
    image: grafana/tempo:2.1.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/otel/tempo.yml:/etc/tempo.yaml
      - /var/lib/docker/volumes/otel/tempo:/tmp/tempo
    restart: unless-stopped
    ports:
      - 3200:3200  # tempo
      - 4007:4317  # otlp grpc
    depends_on:
      - otel-collector
    networks:
      otel:
      
  loki:
    # https://github.com/grafana/loki/releases
    image: grafana/loki:2.8.2
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro      
      - /var/lib/docker/volumes/otel/loki.yml:/etc/loki/local-config.yaml
      - /var/lib/docker/volumes/otel/loki:/data/loki
    restart: unless-stopped
    ports:
      - 3100:3100
    networks:
      otel:
      
  grafana:
    # https://github.com/grafana/grafana/releases
    image: grafana/grafana:9.5.2
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/otel/grafana/data:/var/lib/grafana
      - /var/lib/docker/volumes/otel/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    user: root
    ports:
      - 3001:3000
    depends_on:
      - prometheus
      - tempo
      - loki      
    networks:
      otel:
      
  otel-collector:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/releases
    container_name: otel
    hostname: otel
    image: otel/opentelemetry-collector-contrib:0.78.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - /var/lib/docker/volumes/otel/otel.yml:/etc/otel-collector-config.yaml
    restart: unless-stopped
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
      - "9200:55679"  # zpages
    networks:
      otel:
      
  rabbitmq:
    # https://github.com/docker-library/rabbitmq
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      otel:

networks:
  otel: