receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: otel:8889
  otlp:
    endpoint: tempo:4007
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

extensions:
  zpages:
     endpoint: otel:55679

service:
  extensions: [zpages]  # Enable zpages
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [otlp]
      # exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/logs]
      # exporters: [debug, otlphttp/logs]