scrape_configs:
  - job_name: 'blackbox'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://host.docker.internal:5000/health
        - http://host.docker.internal:5500/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
    - targets: ['otel-collector:8889']
    - targets: ['otel-collector:8888']