#https://grafana.com/docs/grafana/latest/administration/provisioning/
apiVersion: 1

datasources:
- name: Loki
  type: loki
  uid: loki
  access: proxy
  url: http://host.docker.internal:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false