# Install https://github.com/Huachao/vscode-restclient to perform inline REST calls
# Weather API

# Test weatherforecast GET endpoint withouth input parameters
GET http://localhost:5100/weatherforecast

###

# Test weatherforecast GET endpoint with input parameters
GET http://localhost:5100/weatherforecast?latitude=41&longitude=41